lab/Models/preguntaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class preguntaModel
    {
        public string enunciado { get; set; }
        public double respuesta { get; set; }
        public preguntaModel(string enunciado, double respuesta)
        {
            this.enunciado = enunciado;
            this.respuesta = respuesta;
        }
    }

}

lab/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

lab/Controllers/quizzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
namespace WebApplication1.Controllers
{
    public class quizzController : Controller
    {
        // GET: quizz
        public ActionResult pruebaCorta()
        {
            int i = 0;
            preguntaModel[] preguntas = new preguntaModel[20];
            preguntas[0] = new preguntaModel("3x4x5", 60);
            preguntas[1] = new preguntaModel("1+2", 3);
            preguntas[2] = new preguntaModel("10/5", 2);
            preguntas[3] = new preguntaModel("10-9", 1);
            preguntas[4] = new preguntaModel("2x3", 6);
            preguntas[5] = new preguntaModel("15x1", 15);
            preguntas[6] = new preguntaModel("15x3", 45);
            preguntas[7] = new preguntaModel("45x3", 135);
            preguntas[8] = new preguntaModel("1+15", 16);
            preguntas[9] = new preguntaModel("2+8", 10);
            preguntas[10] = new preguntaModel("6-3", 3);
            preguntas[11] = new preguntaModel("3x3", 9);
            preguntas[12] = new preguntaModel("60-50", 10);
            preguntas[13] = new preguntaModel("20x3", 60);
            preguntas[14] = new preguntaModel("1+9", 10);
            preguntas[15] = new preguntaModel("3x3x3", 27);
            preguntas[16] = new preguntaModel("3x4x6", 72);
            preguntas[17] = new preguntaModel("5!", 120);
            preguntas[18] = new preguntaModel("1+2+3", 6);
            preguntas[19] = new preguntaModel("15x2", 30);
            @ViewBag.preguntas = preguntas;
            return View();
        }
    }
}

lab/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

lab/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

lab/Views/Home/Index.cshtml
@{
        ViewBag.Title = "Home Page";

}

<div class="jumbotron">
    <h3>Laboratorio#6:Introducción a JavaScript y CSS</h3>
    <p class="lead">Este laboratorio fue elaboarado por Eduardo Ayales, José David Ureña y José David Delgado</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>
<h5>En el apartado de quizz en la barra de navegación se puede llevar a cabo la prueba corta</h5>

lab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Quizz", "pruebaCorta", "quizz")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

lab/Views/quizz/pruebaCorta.cshtml
@{
    ViewBag.Title = "Prueba Corta";
}
<style>
    h2 {
        margin-bottom: 20px;
    }
</style>

<h2>@ViewBag.Title</h2>
<div class="mb-3">
    <label id="label" for="cantidad" class="form-label">Indique la cantidad de preguntas (5-20)</label> <br />
    <input type="number" class="form-control" id="cantidad" min=5 max=20 placeholder="Escribe aquí el valor numérico">
</div>
<br />
<button id="buttonInicial" onclick="show()" type="button">Continuar</button>
<br />

@for (var i = 0; i < 20; ++i)
{
    <div class="mb-3">
        <label id="label @i" for="Pregunta @i" class="form-label">@ViewBag.preguntas[i].enunciado</label> <br />
        <input type="number" class="form-control" id="Pregunta @i" placeholder="Escribe aquí la respuesta">
    </div>
    <p id="correct @i"></p>
}
<button id="button1" onclick="verRespuestas()" type="button">Ver Respuestas correctas</button>
<button id="button2" onclick="revisar()" type="button">Revisar mis respuestas</button>


<script>
    window.onload = hideAll();
    function hideAll() {
        document.getElementById("button1").style.display = 'none'
        document.getElementById("button2").style.display = 'none'
        for (let i = 0; i < 20; ++i) {
            document.getElementById('Pregunta ' + i).style.display = 'none'
            document.getElementById('correct ' + i).style.display = 'none'
            document.getElementById('label ' + i).style.display = 'none'

        }
    }
    function verRespuestas() {
        console.log('Hello world!!')
        let answers = [60, 3, 2, 1, 6, 15, 45, 135, 16, 10, 3, 9, 10, 60, 10, 27, 72, 120, 6, 30];
        for (let i = 0; i < 20; ++i) {
            document.getElementById('correct ' + i).style.display = 'none'
            document.getElementById("Pregunta " + i).value = answers[i];
        }
    }
    function isCorrect(questionNumber) {
        let answers = [60, 3, 2, 1, 6, 15, 45, 135, 16, 10, 3, 9, 10, 60, 10, 27, 72, 120, 6, 30];
        if (document.getElementById('Pregunta ' + questionNumber).value != answers[questionNumber]) {
            document.getElementById('correct ' + questionNumber).innerHTML = '<strong> Error  , la respuesta correcta es: ' + answers[questionNumber] + "</strong >"
        }
        else {
            document.getElementById('correct ' + questionNumber).innerHTML = '<strong>Respuesta Correcta!!</strong>';
        }
    }
    function revisar() {
        console.log('revisado')
        for (let i = 0; i < 20; ++i) {
            isCorrect(i);
        }
    }
    function show() {
        let limSuperior = document.getElementById('cantidad').value;
        for (let i = 0; i < limSuperior; ++i) {
            document.getElementById('Pregunta ' + i).style.display = 'block'
            document.getElementById('correct ' + i).style.display = 'block'
            document.getElementById('label ' + i).style.display = 'block'
        }
    }
    document.getElementById('button1').style.display = 'block'
    document.getElementById('button2').style.display = 'block'
</script>